# Site settings
title: Hello World,
email: henryachen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simple is Smart
baseurl: "" # the subpath of your site, e.g. /blog/
url: "henryachen.github.io" # the base hostname & protocol for your site
github_username:  henryachen

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true