# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Henry Chen
tagline:          'Curiously Curious'
description:      'a humble introduction'
url:              henryachen.github.io
baseurl:          /

author:
  name:           'Henry Chen'


paginate:         1


